version: "3.11"
services:
 app:
  build: .
  volumes:
   - .:/chat_app
  ports:
   - 8000:8000
  image: app:chat_app
  container_name: chat_app_container
  command: python manage.py runserver 0.0.0.0:8000